// frontend/src/views/LoginSuccess.vue
<script setup>
import { onMounted } from 'vue'
import {useRoute, useRouter} from 'vue-router'

const router = useRouter()
const route = useRoute();
const token = String(route.query.token || "");

onMounted(() => {
  if(token) {
    localStorage.setItem('accessToken', token);
  }

  setTimeout(() => {
    router.push('/home')
  }, 500)
})
</script>

<template>
  <div class="success-container">
    <h2>Login Successful!</h2>
    <p>Redirecting you...</p>
  </div>
</template>

<style scoped>
.success-container {
  text-align: center;
  padding-top: 5rem;
}
</style>

// frontend-react/src/views/LoginSuccess.jsx
import React, { useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import './LoginSuccess.css';

const LoginSuccess = () => {
    const navigate = useNavigate();
    const [searchParams] = useSearchParams();
    const token = searchParams.get('token');

    useEffect(() => {
        if (token) {
            localStorage.setItem('accessToken', token);
        }

        const timer = setTimeout(() => {
            navigate('/home');
        }, 500);

        return () => clearTimeout(timer);
    }, [token, navigate]);

    return (
        <div className="success-container">
            <h2>Login Successful!</h2>
            <p>Redirecting you...</p>
        </div>
    );
};

export default LoginSuccess;
