// frontend-react/src/views/LoginFailure.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const LoginFailure = () => {
    return (
        <div style={{ textAlign: 'center', paddingTop: '5rem' }}>
            <h2 style={{ color: '#ff4d4d' }}>Login Failed</h2>
            <p>Something went wrong during authentication.</p>
            <Link to="/" style={{ color: '#4a90e2', textDecoration: 'none' }}>Back to Login</Link>
        </div>
    );
};

export default LoginFailure;

// frontend/src/views/LoginFailure.vue
<script setup>
import { useRouter } from 'vue-router'

const router = useRouter()
</script>

<template>
  <div class="failure-container">
    <h2>Login Failed</h2>
    <p>Something went wrong during authentication.</p>
    <button @click="router.push('/')">Try Again</button>
  </div>
</template>

<style scoped>
.failure-container {
  text-align: center;
  padding-top: 5rem;
  color: #ff6b6b;
}
</style>
